# Generated by Django 3.2.5 on 2021-11-20 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crwaling_Live',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('death', models.TextField()),
                ('serious', models.TextField()),
                ('new_hospitalization', models.TextField()),
                ('confirmed', models.TextField()),
            ],
            options={
                'db_table': 'covid',
            },
        ),
    ]
